// <auto-generated />
namespace SKUPromotions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SKU22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SKU22));
        
        string IMigrationMetadata.Id
        {
            get { return "202007310545019_SKU22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
