USE [master]
GO
/****** Object:  Database [SKUShipping]    Script Date: 7/31/2020 11:38:43 AM ******/
CREATE DATABASE [SKUShipping]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SKUShipping', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SKUShipping.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SKUShipping_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SKUShipping_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SKUShipping] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SKUShipping].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SKUShipping] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SKUShipping] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SKUShipping] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SKUShipping] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SKUShipping] SET ARITHABORT OFF 
GO
ALTER DATABASE [SKUShipping] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SKUShipping] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SKUShipping] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SKUShipping] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SKUShipping] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SKUShipping] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SKUShipping] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SKUShipping] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SKUShipping] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SKUShipping] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SKUShipping] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SKUShipping] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SKUShipping] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SKUShipping] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SKUShipping] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SKUShipping] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SKUShipping] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SKUShipping] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SKUShipping] SET  MULTI_USER 
GO
ALTER DATABASE [SKUShipping] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SKUShipping] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SKUShipping] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SKUShipping] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SKUShipping] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SKUShipping] SET QUERY_STORE = OFF
GO
USE [SKUShipping]
GO
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 7/31/2020 11:38:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PromotionEntities]    Script Date: 7/31/2020 11:38:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PromotionEntities](
	[PromoId] [int] IDENTITY(1,1) NOT NULL,
	[PromoNm] [nvarchar](max) NULL,
	[PromoProductNm] [nvarchar](max) NULL,
	[ProductPromoNumber] [int] NOT NULL,
	[PromoValue] [float] NOT NULL,
	[PromoType] [nvarchar](max) NULL,
	[CreatedBy] [nvarchar](max) NULL,
	[UpdatedBy] [nvarchar](max) NULL,
	[CreatedDt] [datetime] NOT NULL,
	[UpdatedDt] [datetime] NOT NULL,
	[MachineNm] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.PromotionEntities] PRIMARY KEY CLUSTERED 
(
	[PromoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SKUProductsDetails]    Script Date: 7/31/2020 11:38:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SKUProductsDetails](
	[SKUProductId] [int] IDENTITY(1,1) NOT NULL,
	[SKUProductNm] [nvarchar](max) NULL,
	[CreatedBy] [nvarchar](max) NULL,
	[UpdatedBy] [nvarchar](max) NULL,
	[CreatedDt] [datetime] NOT NULL,
	[UpdatedDt] [datetime] NOT NULL,
	[MachineNm] [nvarchar](max) NULL,
	[ProductPrice] [float] NOT NULL,
 CONSTRAINT [PK_dbo.SKUProductsDetails] PRIMARY KEY CLUSTERED 
(
	[SKUProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SKUProductsDetails] ADD  DEFAULT ((0)) FOR [ProductPrice]
GO
USE [master]
GO
ALTER DATABASE [SKUShipping] SET  READ_WRITE 
GO
